name: Functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }}
          MULTI_CONTAINS_FUNC: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}', 'Hi', 'world') }}
          JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }}
  dump:
    runs-on: ubuntu-latest