name: GITHUB_OUTPUT
run-name: Run by @${{ github.actor }}
on: push
jobs:
  print:
    name: Super Useful Job
    runs-on: ubuntu-latest
    steps:
      - name: Amazing Script
        run: echo "Hello"

  share:
    runs-on: ubuntu-latest
    # ステップを跨いで値を共有する方法
    # idとキーバリュー形式の変数を指定することで参照先を特定
    steps:
      - id: source
        run: echo "result=Hello" >> "$GITHUB_OUTPUT"
      - env:
          RESULT: ${{ steps.source.outputs.result }}
        run: echo "${RESULT}"