name: Log group
on: workflow_dispatch
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      # ::group::ロググループ化の開始
      # ::endgroup::ロググループ化の終了
      - run: |
          echo "::group::Show environment variables"
          printenv
          echo "::endgroup::"
      - run: echo "::add-mask::This is password  # ログ出力時をマスク
      - run: echo "::error::This is an error"    # Errorレベルのアノテーション
      - run: echo "::warning::This is a warning" # Warningレベルのアノテーション
      - run: echo "::notice::This is a notice"   # Noticeレベルのアノテーション"
      - run: | # マークダウンテキストをジョブサマリーへ出力
          echo "## Example Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
          echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
          echo "- second line" >> "${GITHUB_STEP_SUMMARY}"